# -*- coding: utf-8 -*-
"""pds4&5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jweRlL3aHzYbQWALCTeukltQin3StFci
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Assignment 4&5/diabetes.csv')

df.head()

duplicates = df.duplicated()

duplicates

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)

sample = df.sample(n=25)

sample_mean=sample['Glucose'].mean()
sample_max=sample['Glucose'].max()

population_mean=df['Glucose'].mean()
population_max=df['Glucose'].max()

labels = ['Sample Mean', 'Sample Max', 'Population Mean', 'Population Max']
values = [sample_mean, sample_max, population_mean, population_max]
colors = ['blue', 'orange', 'green', 'red']
plt.barh(labels, values, color=colors)
plt.xlabel('Glucose Value')
plt.title('Comparison of Glucose Statistics')
plt.yticks(rotation=45)
plt.show()

