# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lyr5xeZeignzhIDaj5s8kD6hFdml2Q5E
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Assignment 4&5/diabetes.csv')

sample=df.sample(n=25)

sample_bmi_98th_percentile = np.percentile(df['BMI'].sample(n=25), 98)

population_bmi_98th_percentile = np.percentile(df['BMI'], 98)

plt.barh(['Sample 98th Percentile', 'Population 98th Percentile'], [sample_bmi_98th_percentile, population_bmi_98th_percentile], color=['blue', 'orange'])
plt.xlabel('BMI')
plt.title('Comparison of 98th Percentile of BMI')
plt.yticks(rotation=45)
plt.show()

